# Para usar un secret en un pod, se debe crear un secret y luego referenciarlo en el pod.
# En este caso, se crea un secret con el nombre my-secret y se referencia en el pod con el nombre my-secret y la key username.
# El secret debe de estar en base64. echo "fernando" | base64
# Dentro del contenedor se puede acceder a la variable de entorno USERNAME. usando echo $USERNAME

apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: ZmVybmFuZG8K

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    tty: true
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
